replicaCount: 1

image:
  repository: quay.io/varkrish/crew-skills-service
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 8090

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: crew-skills.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

env:
  SKILLS_BASE_DIRS: /app/skills/base
  SKILLS_INDEX_CACHE_DIR: /app/cache

persistence:
  cache:
    enabled: true
    size: 2Gi
    storageClass: ""
    accessMode: ReadWriteOnce

resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 1Gi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}
