{{- if .Values.jiraSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "connector.fullname" . }}-secret
  labels:
    {{- include "connector.labels" . | nindent 4 }}
type: Opaque
stringData:
  JIRA_EMAIL: {{ .Values.jiraSecret.JIRA_EMAIL | quote }}
  JIRA_API_TOKEN: {{ .Values.jiraSecret.JIRA_API_TOKEN | quote }}
  JIRA_USERNAME: {{ .Values.jiraSecret.JIRA_USERNAME | quote }}
  JIRA_PASSWORD: {{ .Values.jiraSecret.JIRA_PASSWORD | quote }}
  JIRA_PERSONAL_ACCESS_TOKEN: {{ .Values.jiraSecret.JIRA_PERSONAL_ACCESS_TOKEN | quote }}
  JIRA_PROJECT_KEYS: {{ .Values.jiraSecret.JIRA_PROJECT_KEYS | quote }}
  JIRA_WEBHOOK_SECRET: {{ .Values.jiraSecret.JIRA_WEBHOOK_SECRET | quote }}
  LLM_API_BASE_URL: {{ .Values.jiraSecret.LLM_API_BASE_URL | quote }}
  LLM_API_KEY: {{ .Values.jiraSecret.LLM_API_KEY | quote }}
{{- end }}
