apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-workspace
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.workspace.accessMode }}
  {{- if .Values.persistence.workspace.storageClass }}
  storageClassName: {{ .Values.persistence.workspace.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.workspace.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-backend-data
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.data.accessMode }}
  {{- if .Values.persistence.data.storageClass }}
  storageClassName: {{ .Values.persistence.data.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
