replicaCount: 1

image:
  repository: docker.io/atlassian/jira-software
  pullPolicy: IfNotPresent
  tag: "9.4.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 8080

route:
  enabled: false
  host: ""
  annotations: {}
  tls:
    enabled: true
    termination: edge
    insecureEdgeTerminationPolicy: Redirect

persistence:
  enabled: true
  size: 10Gi
  storageClass: ""
  accessMode: ReadWriteOnce

resources:
  requests:
    cpu: "1"
    memory: 2Gi
  limits:
    cpu: "4"
    memory: 8Gi

autoscaling:
  enabled: false

nodeSelector: {}
tolerations: []
affinity: {}
