{{- if .Values.persistence.cache.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "skills-service.fullname" . }}-cache
  labels:
    {{- include "skills-service.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.cache.accessMode }}
  {{- if .Values.persistence.cache.storageClass }}
  storageClassName: {{ .Values.persistence.cache.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.cache.size }}
{{- end }}
